### ISSUE TITLE
Project V1 Feedback

### ISSUE THREAD

**Issue by annieliu2** [mmadison1/Project#3]
Content
-you could add a page of safety tips while traveling abroad
-you can add information about essentials to pack

Technical
-in the navigation, you can include the different cities as a drop-down menu from the cities I traveled to tab
-i couldn't access anything else besides the homepage and the sitemap
-also your website says not secure next to the url, I wonder if you could fix that

**Comment by mmadison1** [comment]
I like your idea of adding safety measures. Thanks! The links to the other pages are now open thank you!
