### ISSUE TITLE
Project V1 PeerReview

### ISSUE THREAD

**Issue by jhoffman12** [mmadison1/Project#4]
Content:
1. On your introduction page make sure to also put Barcelona on the list of places you visited even though that was where you spent most of your time
2.  When you create the cities traveled  to page maybe link the city names from your home page to thee spot on the page you can find the description  on that visit
Technical:
1. Your sight said it was not protected and I had to go through extra steps to gain access to it.
2. Maybe consider maintaining the same formatting  for the  sitemap page that you currently have for the rest of the blog

**Comment by mmadison1** [comment]
Thank you! I will continue to fix these issues!
