### ISSUE TITLE
Proj V1 peer review

### ISSUE THREAD

**Issue by elitvak1** [mmadison1/Project#5]
Great color design. Awesome background picture that gives the website depth. Great link bar. very impressive.

Great start and theres not much more you need to do. I recommend centering the links within the div. you should also find social media icons that don't have background (cutouts) and also decrease there sizes and maybe center them. You may want to use a dark shade of pink on your table.
Great content. very indepth. some of the images are weirdly sized and positioned. 
All together a very pretty and engaging website. Sounds like you had a lot of fun in Barcelona!

**Comment by mmadison1** [comment]
thank you!
